from __future__ import annotations

from typing import Protocol

from cys_core.domain.catalog.models import ProfilePolicyPayload


class ProfilePolicyPort(Protocol):
    def get_policy(self, profile_id: str) -> ProfilePolicyPayload: ...

    def get_trust_floor(self, profile_id: str) -> float: ...

    def get_bus_policy(self, profile_id: str) -> dict[str, list[str]]: ...

    def get_escalation_paths(self, profile_id: str) -> set[tuple[str, str]]: ...

    def get_hitl_threshold(self, profile_id: str) -> str: ...

    def get_max_spawn_depth(self, profile_id: str) -> int: ...

    def get_cost_per_1k_tokens(self, profile_id: str) -> float: ...

    def get_notify_control_severities(self, profile_id: str) -> set[str]: ...
