"""Generate architecture debt inventory (markdown table) from AST imports."""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "cys_core"
APPLICATION = CORE / "application"
REGISTRY = CORE / "registry"

PREFIXES: dict[str, str] = {
    "interfaces.": "interfaces",
    "bootstrap.": "bootstrap",
    "cys_core.infrastructure.": "infrastructure",
    "cys_core.registry.": "registry",
    "cys_core.observability.": "observability",
    "cys_core.runtime.": "runtime",
}

TARGET_PHASE: dict[str, str] = {
    "interfaces": "Phase 4",
    "bootstrap": "Phase 7",
    "infrastructure": "Phase 5",
    "registry": "Phase 5",
    "observability": "Phase 7",
    "runtime": "Phase 6",
}


def _imports_in_file(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                found.add(alias.name)
        elif isinstance(node, ast.ImportFrom) and node.module:
            found.add(node.module)
    return found


def _category(mod: str) -> str | None:
    for prefix, cat in PREFIXES.items():
        if mod.startswith(prefix):
            return cat
    return None


def scan_application() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    if not APPLICATION.exists():
        return rows
    for path in sorted(APPLICATION.rglob("*.py")):
        rel = path.relative_to(ROOT).as_posix()
        for mod in sorted(_imports_in_file(path)):
            cat = _category(mod)
            if cat:
                rows.append((rel, mod, cat))
    return rows


def scan_registry_interfaces() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    if not REGISTRY.exists():
        return rows
    for path in sorted(REGISTRY.rglob("*.py")):
        rel = path.relative_to(ROOT).as_posix()
        for mod in sorted(_imports_in_file(path)):
            if mod.startswith("interfaces."):
                rows.append((rel, mod))
    return rows


def render_markdown() -> str:
    lines = [
        "# Architecture Debt Inventory",
        "",
        "Auto-generated by `scripts/arch_inventory.py`. See [ARCHITECTURE_DEBT.md](../docs/ARCHITECTURE_DEBT.md) for curated notes.",
        "",
        "## Application layer violations",
        "",
        "| File | Import | Category | Target phase |",
        "|------|--------|----------|--------------|",
    ]
    for rel, mod, cat in scan_application():
        lines.append(f"| `{rel}` | `{mod}` | {cat} | {TARGET_PHASE[cat]} |")
    lines.extend(
        [
            "",
            "## Registry → interfaces",
            "",
            "| File | Import | Target phase |",
            "|------|--------|--------------|",
        ]
    )
    for rel, mod in scan_registry_interfaces():
        lines.append(f"| `{rel}` | `{mod}` | Phase 4 |")
    return "\n".join(lines) + "\n"


def main() -> int:
    sys.stdout.write(render_markdown())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
