from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol


class MetricsPort(Protocol):
    def record_persistence_fallback(self, component: str) -> None: ...

    def record_event_ingested(self, event_type: str) -> None: ...

    def record_job_usage(self, persona: str, *, tokens: int, cost_usd: float) -> None: ...

    def record_sgr_iron_parse_retry(self) -> None: ...

    def set_agent_trust_score(self, persona: str, score: float) -> None: ...

    def record_memory_read(self, tenant: str, *, entries_loaded: int) -> None: ...

    def record_memory_write(self, tenant: str, memory_type: str) -> None: ...

    def record_sanitizer_block(self, source: str, verdict: str) -> None: ...

    def record_bus_dedup_dropped(self, reason: str) -> None: ...

    def record_engagement_guardrail_trip(self, reason: str) -> None: ...

    def track_worker_job(self, persona: str) -> AbstractContextManager[dict[str, str]]: ...

    def record_worker_job_timeout(self, persona: str) -> None: ...

    def record_worker_job_failure(self, persona: str, reason: str) -> None: ...

    def record_bus_enqueue_rejected_off_plan(self, reason: str) -> None: ...

    def record_bus_revision_rejected(self, reason: str) -> None: ...

    def record_planner_stuck_fallback(self) -> None: ...

    def record_worker_job_salvaged(self, persona: str, reason: str) -> None: ...

    def record_follow_up_queued(self, work_kind: str) -> None: ...
